### ISSUE TITLE
Drop JS Requirement

### ISSUE THREAD

**Issue by CSDUMMI** [iv-org/invidious-redirect#8]
The invidious redirect page is a very simple and straight forward site,
that should not require the use JS.

And it should thus be dropped entirely.

**Comment by unixfox** [comment]
It doesn't require any JS at all, you can still click on one of the randomized instances.
It just that it doesn't include the path in each randomized instance when JS is not enabled. Unfortunately, we aren't going to provide this functionality for the users that don't have JS enabled because it would require to host the website on our own servers.
Currently, the website is served by GitHub pages, doesn't occur any costs and can serve a lot of requests at the same time.
